# Generated by Django 4.0.5 on 2022-07-15 06:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0002_userlogs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlogs',
            name='time_in',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
