# Generated by Django 4.0.5 on 2022-08-10 05:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('dashboards', '0003_alter_userlogs_time_in'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignerProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterModelOptions(
            name='userlogs',
            options={'verbose_name_plural': 'user logs'},
        ),
    ]
