# Generated by Django 4.0.5 on 2022-08-10 05:11

import dashboards.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0004_designerprofile_alter_userlogs_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='designerprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=dashboards.models.save_image_location),
        ),
    ]
