# Generated by Django 4.0.4 on 2022-05-10 06:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaskCategory',
            fields=[
                ('basetime_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tasks.basetime')),
                ('name', models.CharField(max_length=120)),
                ('task_point', models.FloatField(default=0.0)),
            ],
            options={
                'verbose_name_plural': 'Task Categories',
            },
            bases=('tasks.basetime', models.Model),
        ),
        migrations.CreateModel(
            name='TaskType',
            fields=[
                ('basetime_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tasks.basetime')),
                ('name', models.CharField(max_length=60)),
            ],
            bases=('tasks.basetime', models.Model),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Client name')),
                ('paradise_link', models.URLField(blank=True, null=True)),
                ('is_priority', models.BooleanField(default=False, help_text='Check if task is priority.', verbose_name='Is Priority?')),
                ('is_done', models.BooleanField(default=False, help_text='Note: Before ckecking the box be sure task checklist are completed. All assets are uploaded to there specific folder locations.', verbose_name='Is done?')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('task_category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tasks.taskcategory')),
                ('task_type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tasks.tasktype')),
            ],
            options={
                'ordering': ['is_done', '-updated', '-created'],
            },
        ),
        migrations.CreateModel(
            name='TaskRemark',
            fields=[
                ('basetime_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tasks.basetime')),
                ('remarks', models.TextField()),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.task')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated', '-created'],
            },
            bases=('tasks.basetime', models.Model),
        ),
    ]
