# Generated by Django 4.0.5 on 2022-06-07 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_task_check_list_link_alter_task_is_done_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasktype',
            name='task_point',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='task',
            name='check_list_link',
            field=models.URLField(blank=True, max_length=120, null=True, verbose_name='check list link'),
        ),
    ]
