# Generated by Django 4.0.5 on 2022-06-21 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_tasktype_task_point_alter_task_check_list_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskcategory',
            name='name',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
