# Generated by Django 4.0.5 on 2022-07-06 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_alter_task_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='is_done',
            field=models.BooleanField(default=False, help_text="Note: Checked if you're done.", verbose_name='Is Task Completed?'),
        ),
        migrations.AlterField(
            model_name='task',
            name='is_priority',
            field=models.BooleanField(default=False, help_text='Checked if task is priority.', verbose_name='Is Task Priority?'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='TaskCategory', to='tasks.taskcategory'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='TaskType', to='tasks.tasktype'),
        ),
    ]
