# Generated by Django 4.0.5 on 2022-07-06 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_alter_task_is_done_alter_task_is_priority_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tasks.taskcategory'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tasks.tasktype'),
        ),
    ]
