# Generated by Django 4.0.5 on 2022-07-06 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_alter_task_task_category_alter_task_task_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_note',
            field=models.TextField(blank=True, help_text='Task note for designers', null=True),
        ),
    ]
