# Generated by Django 4.0.5 on 2022-07-06 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_task_task_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='task_note',
        ),
    ]
