# Generated by Django 4.0.5 on 2022-07-07 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_alter_task_created_alter_task_updated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-is_priority', 'is_done', '-updated', '-created']},
        ),
    ]
