# Generated by Django 4.0.5 on 2023-02-10 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0016_alter_task_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
                ('is_done', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='task',
            name='check_list_link',
        ),
        migrations.AlterField(
            model_name='taskremark',
            name='remarks',
            field=models.TextField(help_text='You can use html elements for your notes'),
        ),
        migrations.CreateModel(
            name='CheckListType',
            fields=[
                ('basetime_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tasks.basetime')),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
                ('check_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.checklist')),
            ],
            bases=('tasks.basetime', models.Model),
        ),
    ]
