# Generated by Django 4.0.5 on 2023-02-10 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0017_checklist_remove_task_check_list_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklist',
            name='is_done',
        ),
        migrations.AddField(
            model_name='checklisttype',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
